name: Docker Build and Push

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Images
      run: |
        docker build -t backend-image:latest ./backend
        docker build -t frontend-image:latest ./frontend

    - name: Install Mocha
      run: npm install -g mocha
      if: success()  # Only run this step if previous steps were successful
      
    - name: Install Dependencies and Run Tests (Frontend)
      working-directory: frontend
      run: |
        npm install
        mocha
        npm test

    - name: Install Dependencies and Run Tests (Backend)
      working-directory: backend
      run: |
        npm install
        npm test

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Images
      run: |
        docker push backend-image:latest
        docker push frontend-image:latest
